### ISSUE TITLE
can you update???

### ISSUE THREAD

**Issue by matheusbranhann** [poruto/rustcheat-python#1]

**Comment by matheusbranhann** [comment]
can you update??? #1

**Comment by matheusbranhann** [comment]
any guy have the offsets from this source updated?

        gomaddress = 0x17C1F18
        basenetworkable = 54625768
        off_playermodel = 0x4C0
        off_inventory = 0x690
        off_activegun = 0x5D0
        off_displayname = 0x6E0

**Comment by poruto** [comment]
This will never work on EAC enabled servers, unless huge changes are made.

No update is planned.

**Comment by matheusbranhann** [comment]
I know, but I'm using this project as a basis to use a reading driver that I'm manipulating, but I'm not able to get the offsets to update, unfortunately.

**Comment by matheusbranhann** [comment]
My problem currently is the offsets, I don't know how to get them and I would like a project with them updated to learn, you know?

**Comment by poruto** [comment]
I really doubt you will get anything to work when you need to ask for offsets.

Getting offsets is much easier done, even with a quick internet search than writing a driver.

**Comment by matheusbranhann** [comment]
> I really doubt you will get anything to work when you need to ask for offsets.
> 
> Getting offsets is much easier done, even with a quick internet search than writing a driver.

thanks anyway
